#!/bin/bash

# Define colors for echoing steps
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Install Google Chrome using paru
echo -e "${GREEN}Installing Google Chrome with paru...${NC}"
paru -S google-chrome --noconfirm

echo -e "${GREEN}Google Chrome installation completed!${NC}"
