#!/usr/bin/env bash

# Arch Linux Docker installation
# https://wiki.archlinux.org/title/Docker

paru -S docker docker-compose --noconfirm --needed

sudo systemctl enable --now docker
sudo groupadd docker
sudo usermod -aG docker $USER
