#!/usr/bin/env bash

# Arch Linux Docker installation
# https://wiki.archlinux.org/title/Docker

sudo pacman -S --needed docker

sudo systemctl enable --now docker
sudo groupadd docker
sudo usermod -aG docker $USER

# Install docker-compose
paru -S docker-compose --noconfirm
