#!/usr/bin/env bash

if [ ! -d $HOME/picom ]; then
    git clone https://github.com/yshui/picom.git $HOME/picom
fi

sudo pacman -S --needed libconfig dbus libev egl-wayland glvnd libepoxy pcre2 pixman libx11 libxcb libxext meson ninja uthash

git -C ~/picom fetch --all
git -C ~/picom checkout

cd $HOME/picom
meson setup --buildtype=release build
ninja -C build

LDFLAGS="-L/path/to/libraries" CPPFLAGS="-I/path/to/headers" meson setup --buildtype=release build

ninja -C build install

rm -rf $HOME/picom
