#!/bin/bash

# Update package list
sudo pacman -Sy

# Install packages using pacman and paru
sudo pacman -S --needed git curl dmenu awesome mpv feh pcmanfm lxappearance qutebrowser obs-studio fzf arandr
sudo pacman -S --needed ripgrep pavucontrol xclip jq tldr shutter python-pip

# Install from AUR using paru
paru -S missioncenter --noconfirm
paru -S zen-browser-bin --noconfirm
paru -S nvidia-dkms --noconfirm
