# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"


[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
format = "via [🐋 $context](blue bold)"

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "


[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
conflicted = "⚔️ "
#ahead = "🏎️ 💨×${count}"
#behind = "🐢×${count}"
#diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝×${count}"
staged = "🗃️ ×${count}"
renamed = "📛×${count}"
deleted = "🗑️ ×${count}"
style = "bright-white"
#format = "$all_status $ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "bold green"
show_always = false
